# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'KGSH_Tester.ui'
#
# Created by: PyQt5 UI code generator 5.5
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_KGSH_Tester(object):
    def setupUi(self, KGSH_Tester):
        KGSH_Tester.setObjectName("KGSH_Tester")
        KGSH_Tester.resize(390, 460)
        KGSH_Tester.setMinimumSize(QtCore.QSize(390, 460))
        KGSH_Tester.setMaximumSize(QtCore.QSize(390, 460))
        KGSH_Tester.setMouseTracking(False)
        icon = QtGui.QIcon()
        icon.addPixmap(QtGui.QPixmap("19gear.ico"), QtGui.QIcon.Normal, QtGui.QIcon.Off)
        KGSH_Tester.setWindowIcon(icon)
        KGSH_Tester.setAnimated(True)
        KGSH_Tester.setDockOptions(QtWidgets.QMainWindow.AnimatedDocks)
        self.centralwidget = QtWidgets.QWidget(KGSH_Tester)
        self.centralwidget.setObjectName("centralwidget")
        self.comboBox_Baudrate = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Baudrate.setGeometry(QtCore.QRect(89, 28, 74, 20))
        self.comboBox_Baudrate.setObjectName("comboBox_Baudrate")
        self.comboBox_COM = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_COM.setGeometry(QtCore.QRect(9, 28, 74, 20))
        self.comboBox_COM.setObjectName("comboBox_COM")
        self.label_change_port = QtWidgets.QLabel(self.centralwidget)
        self.label_change_port.setGeometry(QtCore.QRect(9, 9, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.label_change_port.setFont(font)
        self.label_change_port.setObjectName("label_change_port")
        self.pushButton_open_COM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_open_COM.setGeometry(QtCore.QRect(169, 27, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_open_COM.setFont(font)
        self.pushButton_open_COM.setObjectName("pushButton_open_COM")
        self.Label_Volume_t = QtWidgets.QLabel(self.centralwidget)
        self.Label_Volume_t.setGeometry(QtCore.QRect(70, 60, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_Volume_t.setFont(font)
        self.Label_Volume_t.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_Volume_t.setStyleSheet("")
        self.Label_Volume_t.setObjectName("Label_Volume_t")
        self.pushButton_close_COM = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_close_COM.setEnabled(False)
        self.pushButton_close_COM.setGeometry(QtCore.QRect(265, 27, 91, 23))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_close_COM.setFont(font)
        self.pushButton_close_COM.setObjectName("pushButton_close_COM")
        self.pushButton_WDT = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_WDT.setEnabled(False)
        self.pushButton_WDT.setGeometry(QtCore.QRect(290, 80, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_WDT.setFont(font)
        self.pushButton_WDT.setCheckable(False)
        self.pushButton_WDT.setChecked(False)
        self.pushButton_WDT.setDefault(False)
        self.pushButton_WDT.setFlat(False)
        self.pushButton_WDT.setObjectName("pushButton_WDT")
        self.comboBox_Sinus = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox_Sinus.setEnabled(False)
        self.comboBox_Sinus.setGeometry(QtCore.QRect(10, 120, 71, 20))
        self.comboBox_Sinus.setObjectName("comboBox_Sinus")
        self.label_Sinus = QtWidgets.QLabel(self.centralwidget)
        self.label_Sinus.setGeometry(QtCore.QRect(90, 120, 201, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.label_Sinus.setFont(font)
        self.label_Sinus.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Sinus.setStyleSheet("")
        self.label_Sinus.setObjectName("label_Sinus")
        self.frame_1 = QtWidgets.QFrame(self.centralwidget)
        self.frame_1.setGeometry(QtCore.QRect(10, 250, 181, 20))
        self.frame_1.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_1.setObjectName("frame_1")
        self.label_t1 = QtWidgets.QLabel(self.frame_1)
        self.label_t1.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t1.setFont(font)
        self.label_t1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t1.setStyleSheet("")
        self.label_t1.setObjectName("label_t1")
        self.label_1 = QtWidgets.QLabel(self.frame_1)
        self.label_1.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_1.setFont(font)
        self.label_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_1.setStyleSheet("")
        self.label_1.setObjectName("label_1")
        self.frame_2 = QtWidgets.QFrame(self.centralwidget)
        self.frame_2.setGeometry(QtCore.QRect(200, 250, 181, 20))
        self.frame_2.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_2.setObjectName("frame_2")
        self.label_t2 = QtWidgets.QLabel(self.frame_2)
        self.label_t2.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t2.setFont(font)
        self.label_t2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t2.setStyleSheet("")
        self.label_t2.setObjectName("label_t2")
        self.label_2 = QtWidgets.QLabel(self.frame_2)
        self.label_2.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_2.setFont(font)
        self.label_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_2.setStyleSheet("")
        self.label_2.setObjectName("label_2")
        self.Slider_Volume = QtWidgets.QSlider(self.centralwidget)
        self.Slider_Volume.setEnabled(False)
        self.Slider_Volume.setGeometry(QtCore.QRect(10, 80, 231, 21))
        self.Slider_Volume.setMaximum(60)
        self.Slider_Volume.setProperty("value", 0)
        self.Slider_Volume.setOrientation(QtCore.Qt.Horizontal)
        self.Slider_Volume.setObjectName("Slider_Volume")
        self.Label_Volume = QtWidgets.QLabel(self.centralwidget)
        self.Label_Volume.setGeometry(QtCore.QRect(260, 80, 31, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_Volume.setFont(font)
        self.Label_Volume.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_Volume.setStyleSheet("")
        self.Label_Volume.setObjectName("Label_Volume")
        self.frame_LED = QtWidgets.QFrame(self.centralwidget)
        self.frame_LED.setGeometry(QtCore.QRect(10, 180, 371, 61))
        self.frame_LED.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_LED.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_LED.setObjectName("frame_LED")
        self.checkBox_LED_5 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_LED_5.setEnabled(False)
        self.checkBox_LED_5.setGeometry(QtCore.QRect(210, 30, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_LED_5.setFont(font)
        self.checkBox_LED_5.setStyleSheet("")
        self.checkBox_LED_5.setText("")
        self.checkBox_LED_5.setObjectName("checkBox_LED_5")
        self.checkBox_LED_6 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_LED_6.setEnabled(False)
        self.checkBox_LED_6.setGeometry(QtCore.QRect(290, 30, 16, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_LED_6.setFont(font)
        self.checkBox_LED_6.setStyleSheet("")
        self.checkBox_LED_6.setText("")
        self.checkBox_LED_6.setObjectName("checkBox_LED_6")
        self.checkBox_LED_4 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_LED_4.setEnabled(False)
        self.checkBox_LED_4.setGeometry(QtCore.QRect(160, 30, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_LED_4.setFont(font)
        self.checkBox_LED_4.setObjectName("checkBox_LED_4")
        self.Label_LED_Green = QtWidgets.QLabel(self.frame_LED)
        self.Label_LED_Green.setEnabled(False)
        self.Label_LED_Green.setGeometry(QtCore.QRect(310, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_LED_Green.setFont(font)
        self.Label_LED_Green.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_LED_Green.setStyleSheet("color: rgb(2, 161, 0);")
        self.Label_LED_Green.setObjectName("Label_LED_Green")
        self.checkBox_LED_1 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_LED_1.setEnabled(False)
        self.checkBox_LED_1.setGeometry(QtCore.QRect(10, 30, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_LED_1.setFont(font)
        self.checkBox_LED_1.setObjectName("checkBox_LED_1")
        self.checkBox_LED_2 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_LED_2.setEnabled(False)
        self.checkBox_LED_2.setGeometry(QtCore.QRect(60, 30, 51, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_LED_2.setFont(font)
        self.checkBox_LED_2.setObjectName("checkBox_LED_2")
        self.checkBox_LED_3 = QtWidgets.QCheckBox(self.frame_LED)
        self.checkBox_LED_3.setEnabled(False)
        self.checkBox_LED_3.setGeometry(QtCore.QRect(110, 30, 41, 18))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.checkBox_LED_3.setFont(font)
        self.checkBox_LED_3.setObjectName("checkBox_LED_3")
        self.Label_LED_Red = QtWidgets.QLabel(self.frame_LED)
        self.Label_LED_Red.setEnabled(False)
        self.Label_LED_Red.setGeometry(QtCore.QRect(230, 30, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_LED_Red.setFont(font)
        self.Label_LED_Red.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_LED_Red.setStyleSheet("color: rgb(255, 2, 6);")
        self.Label_LED_Red.setObjectName("Label_LED_Red")
        self.Label_Volume_2 = QtWidgets.QLabel(self.frame_LED)
        self.Label_Volume_2.setGeometry(QtCore.QRect(140, 5, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_Volume_2.setFont(font)
        self.Label_Volume_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_Volume_2.setStyleSheet("")
        self.Label_Volume_2.setObjectName("Label_Volume_2")
        self.frame_3 = QtWidgets.QFrame(self.centralwidget)
        self.frame_3.setGeometry(QtCore.QRect(10, 280, 181, 20))
        self.frame_3.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_3.setObjectName("frame_3")
        self.label_t3 = QtWidgets.QLabel(self.frame_3)
        self.label_t3.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t3.setFont(font)
        self.label_t3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t3.setStyleSheet("")
        self.label_t3.setObjectName("label_t3")
        self.label_3 = QtWidgets.QLabel(self.frame_3)
        self.label_3.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_3.setFont(font)
        self.label_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_3.setStyleSheet("")
        self.label_3.setObjectName("label_3")
        self.frame_4 = QtWidgets.QFrame(self.centralwidget)
        self.frame_4.setGeometry(QtCore.QRect(200, 280, 181, 20))
        self.frame_4.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_4.setObjectName("frame_4")
        self.label_t4 = QtWidgets.QLabel(self.frame_4)
        self.label_t4.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t4.setFont(font)
        self.label_t4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t4.setStyleSheet("")
        self.label_t4.setObjectName("label_t4")
        self.label_4 = QtWidgets.QLabel(self.frame_4)
        self.label_4.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_4.setFont(font)
        self.label_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_4.setStyleSheet("")
        self.label_4.setObjectName("label_4")
        self.frame_Key = QtWidgets.QFrame(self.centralwidget)
        self.frame_Key.setGeometry(QtCore.QRect(10, 310, 371, 121))
        self.frame_Key.setFrameShape(QtWidgets.QFrame.StyledPanel)
        self.frame_Key.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key.setObjectName("frame_Key")
        self.Label_Volume_3 = QtWidgets.QLabel(self.frame_Key)
        self.Label_Volume_3.setGeometry(QtCore.QRect(70, 5, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_Volume_3.setFont(font)
        self.Label_Volume_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_Volume_3.setStyleSheet("")
        self.Label_Volume_3.setObjectName("Label_Volume_3")
        self.frame_Key_8 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_8.setGeometry(QtCore.QRect(190, 90, 171, 20))
        self.frame_Key_8.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_8.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_8.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_8.setObjectName("frame_Key_8")
        self.label_t_Key_8 = QtWidgets.QLabel(self.frame_Key_8)
        self.label_t_Key_8.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_8.setFont(font)
        self.label_t_Key_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_8.setStyleSheet("")
        self.label_t_Key_8.setObjectName("label_t_Key_8")
        self.label_Key_8 = QtWidgets.QLabel(self.frame_Key_8)
        self.label_Key_8.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_8.setFont(font)
        self.label_Key_8.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_8.setStyleSheet("")
        self.label_Key_8.setObjectName("label_Key_8")
        self.frame_Key_6 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_6.setGeometry(QtCore.QRect(190, 50, 171, 20))
        self.frame_Key_6.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_6.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_6.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_6.setObjectName("frame_Key_6")
        self.label_t_Key_6 = QtWidgets.QLabel(self.frame_Key_6)
        self.label_t_Key_6.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_6.setFont(font)
        self.label_t_Key_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_6.setStyleSheet("")
        self.label_t_Key_6.setObjectName("label_t_Key_6")
        self.label_Key_6 = QtWidgets.QLabel(self.frame_Key_6)
        self.label_Key_6.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_6.setFont(font)
        self.label_Key_6.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_6.setStyleSheet("")
        self.label_Key_6.setObjectName("label_Key_6")
        self.frame_Key_7 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_7.setGeometry(QtCore.QRect(190, 70, 171, 20))
        self.frame_Key_7.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_7.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_7.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_7.setObjectName("frame_Key_7")
        self.label_t_Key_7 = QtWidgets.QLabel(self.frame_Key_7)
        self.label_t_Key_7.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_7.setFont(font)
        self.label_t_Key_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_7.setStyleSheet("")
        self.label_t_Key_7.setObjectName("label_t_Key_7")
        self.label_Key_7 = QtWidgets.QLabel(self.frame_Key_7)
        self.label_Key_7.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_7.setFont(font)
        self.label_Key_7.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_7.setStyleSheet("")
        self.label_Key_7.setObjectName("label_Key_7")
        self.frame_Key_5 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_5.setGeometry(QtCore.QRect(190, 30, 171, 20))
        self.frame_Key_5.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_5.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_5.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_5.setObjectName("frame_Key_5")
        self.label_t_Key_5 = QtWidgets.QLabel(self.frame_Key_5)
        self.label_t_Key_5.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_5.setFont(font)
        self.label_t_Key_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_5.setStyleSheet("")
        self.label_t_Key_5.setObjectName("label_t_Key_5")
        self.label_Key_5 = QtWidgets.QLabel(self.frame_Key_5)
        self.label_Key_5.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_5.setFont(font)
        self.label_Key_5.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_5.setStyleSheet("")
        self.label_Key_5.setObjectName("label_Key_5")
        self.Label_Volume_4 = QtWidgets.QLabel(self.frame_Key)
        self.Label_Volume_4.setGeometry(QtCore.QRect(250, 5, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.Label_Volume_4.setFont(font)
        self.Label_Volume_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.Label_Volume_4.setStyleSheet("")
        self.Label_Volume_4.setObjectName("Label_Volume_4")
        self.frame_Key_1 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_1.setGeometry(QtCore.QRect(10, 30, 171, 20))
        self.frame_Key_1.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_1.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_1.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_1.setObjectName("frame_Key_1")
        self.label_t_Key_1 = QtWidgets.QLabel(self.frame_Key_1)
        self.label_t_Key_1.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_1.setFont(font)
        self.label_t_Key_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_1.setStyleSheet("")
        self.label_t_Key_1.setObjectName("label_t_Key_1")
        self.label_Key_1 = QtWidgets.QLabel(self.frame_Key_1)
        self.label_Key_1.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_1.setFont(font)
        self.label_Key_1.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_1.setStyleSheet("")
        self.label_Key_1.setObjectName("label_Key_1")
        self.frame_Key_4 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_4.setGeometry(QtCore.QRect(10, 90, 171, 20))
        self.frame_Key_4.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_4.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_4.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_4.setObjectName("frame_Key_4")
        self.label_t_Key_4 = QtWidgets.QLabel(self.frame_Key_4)
        self.label_t_Key_4.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_4.setFont(font)
        self.label_t_Key_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_4.setStyleSheet("")
        self.label_t_Key_4.setObjectName("label_t_Key_4")
        self.label_Key_4 = QtWidgets.QLabel(self.frame_Key_4)
        self.label_Key_4.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_4.setFont(font)
        self.label_Key_4.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_4.setStyleSheet("")
        self.label_Key_4.setObjectName("label_Key_4")
        self.frame_Key_2 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_2.setGeometry(QtCore.QRect(10, 50, 171, 20))
        self.frame_Key_2.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_2.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_2.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_2.setObjectName("frame_Key_2")
        self.label_t_Key_2 = QtWidgets.QLabel(self.frame_Key_2)
        self.label_t_Key_2.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_2.setFont(font)
        self.label_t_Key_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_2.setStyleSheet("")
        self.label_t_Key_2.setObjectName("label_t_Key_2")
        self.label_Key_2 = QtWidgets.QLabel(self.frame_Key_2)
        self.label_Key_2.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_2.setFont(font)
        self.label_Key_2.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_2.setStyleSheet("")
        self.label_Key_2.setObjectName("label_Key_2")
        self.frame_Key_3 = QtWidgets.QFrame(self.frame_Key)
        self.frame_Key_3.setGeometry(QtCore.QRect(10, 70, 171, 20))
        self.frame_Key_3.setStyleSheet("background-color: rgb(255, 117, 53);")
        self.frame_Key_3.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_Key_3.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_Key_3.setObjectName("frame_Key_3")
        self.label_t_Key_3 = QtWidgets.QLabel(self.frame_Key_3)
        self.label_t_Key_3.setGeometry(QtCore.QRect(90, 2, 71, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_t_Key_3.setFont(font)
        self.label_t_Key_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_t_Key_3.setStyleSheet("")
        self.label_t_Key_3.setObjectName("label_t_Key_3")
        self.label_Key_3 = QtWidgets.QLabel(self.frame_Key_3)
        self.label_Key_3.setGeometry(QtCore.QRect(9, 3, 61, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_Key_3.setFont(font)
        self.label_Key_3.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_Key_3.setStyleSheet("")
        self.label_Key_3.setObjectName("label_Key_3")
        self.pushButton_Sinus = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton_Sinus.setEnabled(False)
        self.pushButton_Sinus.setGeometry(QtCore.QRect(290, 120, 81, 21))
        font = QtGui.QFont()
        font.setPointSize(9)
        self.pushButton_Sinus.setFont(font)
        self.pushButton_Sinus.setCheckable(True)
        self.pushButton_Sinus.setChecked(False)
        self.pushButton_Sinus.setDefault(False)
        self.pushButton_Sinus.setFlat(False)
        self.pushButton_Sinus.setObjectName("pushButton_Sinus")
        self.frame_U_in = QtWidgets.QFrame(self.centralwidget)
        self.frame_U_in.setGeometry(QtCore.QRect(20, 150, 101, 20))
        self.frame_U_in.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.frame_U_in.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_U_in.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_U_in.setObjectName("frame_U_in")
        self.label_U_in = QtWidgets.QLabel(self.frame_U_in)
        self.label_U_in.setGeometry(QtCore.QRect(9, 3, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_U_in.setFont(font)
        self.label_U_in.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_U_in.setStyleSheet("")
        self.label_U_in.setObjectName("label_U_in")
        self.frame_U_out = QtWidgets.QFrame(self.centralwidget)
        self.frame_U_out.setGeometry(QtCore.QRect(140, 150, 101, 20))
        self.frame_U_out.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.frame_U_out.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_U_out.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_U_out.setObjectName("frame_U_out")
        self.label_U_out = QtWidgets.QLabel(self.frame_U_out)
        self.label_U_out.setGeometry(QtCore.QRect(9, 3, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_U_out.setFont(font)
        self.label_U_out.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_U_out.setStyleSheet("")
        self.label_U_out.setObjectName("label_U_out")
        self.frame_I_out = QtWidgets.QFrame(self.centralwidget)
        self.frame_I_out.setGeometry(QtCore.QRect(260, 150, 101, 20))
        self.frame_I_out.setStyleSheet("background-color: rgb(150, 150, 150);")
        self.frame_I_out.setFrameShape(QtWidgets.QFrame.Box)
        self.frame_I_out.setFrameShadow(QtWidgets.QFrame.Raised)
        self.frame_I_out.setObjectName("frame_I_out")
        self.label_I_out = QtWidgets.QLabel(self.frame_I_out)
        self.label_I_out.setGeometry(QtCore.QRect(9, 3, 91, 16))
        font = QtGui.QFont()
        font.setPointSize(10)
        self.label_I_out.setFont(font)
        self.label_I_out.setContextMenuPolicy(QtCore.Qt.DefaultContextMenu)
        self.label_I_out.setStyleSheet("")
        self.label_I_out.setObjectName("label_I_out")
        self.frame_LED.raise_()
        self.comboBox_Baudrate.raise_()
        self.comboBox_COM.raise_()
        self.label_change_port.raise_()
        self.pushButton_open_COM.raise_()
        self.Label_Volume_t.raise_()
        self.pushButton_close_COM.raise_()
        self.pushButton_WDT.raise_()
        self.comboBox_Sinus.raise_()
        self.label_Sinus.raise_()
        self.frame_1.raise_()
        self.frame_2.raise_()
        self.Slider_Volume.raise_()
        self.Label_Volume.raise_()
        self.frame_3.raise_()
        self.frame_4.raise_()
        self.frame_Key.raise_()
        self.pushButton_Sinus.raise_()
        self.frame_U_in.raise_()
        self.frame_U_out.raise_()
        self.frame_I_out.raise_()
        KGSH_Tester.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(KGSH_Tester)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 390, 18))
        self.menubar.setObjectName("menubar")
        KGSH_Tester.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(KGSH_Tester)
        self.statusbar.setObjectName("statusbar")
        KGSH_Tester.setStatusBar(self.statusbar)
        self.action = QtWidgets.QAction(KGSH_Tester)
        self.action.setObjectName("action")

        self.retranslateUi(KGSH_Tester)
        QtCore.QMetaObject.connectSlotsByName(KGSH_Tester)

    def retranslateUi(self, KGSH_Tester):
        _translate = QtCore.QCoreApplication.translate
        KGSH_Tester.setWindowTitle(_translate("KGSH_Tester", "Проверка платы управления КГСШ"))
        self.label_change_port.setText(_translate("KGSH_Tester", "Выбор порта"))
        self.pushButton_open_COM.setText(_translate("KGSH_Tester", "Открыть порт"))
        self.Label_Volume_t.setText(_translate("KGSH_Tester", "Громкость"))
        self.pushButton_close_COM.setText(_translate("KGSH_Tester", "Закрыть порт"))
        self.pushButton_WDT.setText(_translate("KGSH_Tester", "WDT"))
        self.label_Sinus.setText(_translate("KGSH_Tester", "Уровень тестового сигнала"))
        self.label_t1.setText(_translate("KGSH_Tester", "не работает"))
        self.label_1.setText(_translate("KGSH_Tester", "CAN"))
        self.label_t2.setText(_translate("KGSH_Tester", "не работает"))
        self.label_2.setText(_translate("KGSH_Tester", "RS-485"))
        self.Label_Volume.setText(_translate("KGSH_Tester", "0"))
        self.checkBox_LED_4.setText(_translate("KGSH_Tester", "4-й"))
        self.Label_LED_Green.setText(_translate("KGSH_Tester", "зеленый"))
        self.checkBox_LED_1.setText(_translate("KGSH_Tester", "1-й"))
        self.checkBox_LED_2.setText(_translate("KGSH_Tester", "2-й"))
        self.checkBox_LED_3.setText(_translate("KGSH_Tester", "3-й"))
        self.Label_LED_Red.setText(_translate("KGSH_Tester", "красный"))
        self.Label_Volume_2.setText(_translate("KGSH_Tester", "Светодиоды"))
        self.label_t3.setText(_translate("KGSH_Tester", "не работает"))
        self.label_3.setText(_translate("KGSH_Tester", "Кодек"))
        self.label_t4.setText(_translate("KGSH_Tester", "не работает"))
        self.label_4.setText(_translate("KGSH_Tester", "Усилитель"))
        self.Label_Volume_3.setText(_translate("KGSH_Tester", "Кнопки"))
        self.label_t_Key_8.setText(_translate("KGSH_Tester", "разомкнут"))
        self.label_Key_8.setText(_translate("KGSH_Tester", "Вход 4"))
        self.label_t_Key_6.setText(_translate("KGSH_Tester", "разомкнут"))
        self.label_Key_6.setText(_translate("KGSH_Tester", "Вход 2"))
        self.label_t_Key_7.setText(_translate("KGSH_Tester", "разомкнут"))
        self.label_Key_7.setText(_translate("KGSH_Tester", "Вход 3"))
        self.label_t_Key_5.setText(_translate("KGSH_Tester", "разомкнут"))
        self.label_Key_5.setText(_translate("KGSH_Tester", "Вход 1"))
        self.Label_Volume_4.setText(_translate("KGSH_Tester", "Входы"))
        self.label_t_Key_1.setText(_translate("KGSH_Tester", "не нажата"))
        self.label_Key_1.setText(_translate("KGSH_Tester", "Кнопка 1"))
        self.label_t_Key_4.setText(_translate("KGSH_Tester", "не нажата"))
        self.label_Key_4.setText(_translate("KGSH_Tester", "Кнопка 4"))
        self.label_t_Key_2.setText(_translate("KGSH_Tester", "не нажата"))
        self.label_Key_2.setText(_translate("KGSH_Tester", "Кнопка 2"))
        self.label_t_Key_3.setText(_translate("KGSH_Tester", "не нажата"))
        self.label_Key_3.setText(_translate("KGSH_Tester", "Кнопка 3"))
        self.pushButton_Sinus.setText(_translate("KGSH_Tester", "Генератор"))
        self.label_U_in.setText(_translate("KGSH_Tester", "U_пит = 0 В"))
        self.label_U_out.setText(_translate("KGSH_Tester", "U_вых = 0 В"))
        self.label_I_out.setText(_translate("KGSH_Tester", "I_вых = 0 мА"))
        self.action.setText(_translate("KGSH_Tester", "Закрыть"))

